name: rental_motor
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  carousel_slider: ^5.0.0
  hexcolor: ^3.0.1
  intl: 0.18.1
  flutter_localization: ^0.2.1
  flutter_map: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vario/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
